version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Frontend SvelteKit
      - "5000:5000"  # API Python YOLO
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/python:/app/src/python:ro  # Volume para desenvolvimento
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000", "&&", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Serviço separado para desenvolvimento do Python
  yolo-dev:
    build: .
    ports:
      - "5001:5000"  # Porta alternativa para desenvolvimento
    command: python3 src/python/yolo_server.py
    volumes:
      - ./src/python:/app/src/python
      - ./requirements.txt:/app/requirements.txt
    profiles:
      - dev
    restart: unless-stopped