version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agenda_contatos_db
    environment:
      POSTGRES_DB: agenda_contatos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: agenda_contatos_app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/agenda_contatos
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./static:/app/static

volumes:
  postgres_data: